version: '3'

services:
  reverse-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

  excalidraw:
    image: excalidraw/excalidraw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Path(`/draw`)"
      - "traefik.http.routers.excalidraw.entrypoints=web, websecure"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
    ports:
      - "5000:80"
    depends_on:
      - reverse-proxy
    networks:
      - web

  feishin:
    image: ghcr.io/jeffvli/feishin
    ports:
      - "9180:9180"
    networks:
      - web

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    volumes:
      - /app/data:/app/data
  
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /path/to/data:/config
      - /path/to/calibre/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  neosmemo-memos:
    image: neosmemo/memos:latest
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - "5230:5230"
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

networks:
  web:
    external: true
