version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.local`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - web

  excalidraw:
    image: excalidraw/excalidraw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.local`)"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
    depends_on:
      - reverse-proxy
    networks:
      - web

networks:
  web:
    external: true
