version: "3"

services:
  excalidraw:
    image: excalidraw/excalidraw
    ports:
      - "5000:80"
    networks:
      - web

  feishin:
    image: ghcr.io/jeffvli/feishin
    ports:
      - "9180:9180"
    networks:
      - web

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    volumes:
      - /app/data:/app/data

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /path/to/data:/config
      - /path/to/calibre/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  dumont:
    image: lnardon/dumont:latest
    container_name: Dumont
    environment:
      - JWT_SIGNING_KEY=SUPER_SECRET_KEY
      - LOGIN_USERNAME=lnardon
      - LOGIN_PASSWORD=supersecretsecret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3322:3322
    restart: always

  neosmemo-memos:
    image: neosmemo/memos:latest
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - "5230:5230"
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

networks:
  web:
    external: true
